//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Director.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Director.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization settings.
        /// </summary>
        internal static string AuthorizationSettings {
            get {
                return ResourceManager.GetString("AuthorizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose running option.
        /// </summary>
        internal static string ChooseRunningOptions {
            get {
                return ResourceManager.GetString("ChooseRunningOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add request.
        /// </summary>
        internal static string ContextMenuAddRequest {
            get {
                return ResourceManager.GetString("ContextMenuAddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove request.
        /// </summary>
        internal static string ContextMenuRemoveRequest {
            get {
                return ResourceManager.GetString("ContextMenuRemoveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove scenario.
        /// </summary>
        internal static string ContextMenuRemoveScenario {
            get {
                return ResourceManager.GetString("ContextMenuRemoveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap default_headers {
            get {
                object obj = ResourceManager.GetObject("default_headers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default headers.
        /// </summary>
        internal static string DefaultServerHeaders {
            get {
                return ResourceManager.GetString("DefaultServerHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scenario file.
        /// </summary>
        internal static string DialogOpenScenario {
            get {
                return ResourceManager.GetString("DialogOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scenario.
        /// </summary>
        internal static string DialogSaveScenario {
            get {
                return ResourceManager.GetString("DialogSaveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notifications.
        /// </summary>
        internal static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request URL!.
        /// </summary>
        internal static string ErroInvalidRequest {
            get {
                return ResourceManager.GetString("ErroInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 10 minutes.
        /// </summary>
        internal static string Every10Minutes {
            get {
                return ResourceManager.GetString("Every10Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 12 hours.
        /// </summary>
        internal static string Every12Hours {
            get {
                return ResourceManager.GetString("Every12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 30 minutes.
        /// </summary>
        internal static string Every30Minutes {
            get {
                return ResourceManager.GetString("Every30Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 3 hours.
        /// </summary>
        internal static string Every3Hours {
            get {
                return ResourceManager.GetString("Every3Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 5 minutes.
        /// </summary>
        internal static string Every5Minutes {
            get {
                return ResourceManager.GetString("Every5Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6 hours.
        /// </summary>
        internal static string Every6Hours {
            get {
                return ResourceManager.GetString("Every6Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every hour.
        /// </summary>
        internal static string EveryHour {
            get {
                return ResourceManager.GetString("EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected status code:.
        /// </summary>
        internal static string ExpectedStatusCode {
            get {
                return ResourceManager.GetString("ExpectedStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export scenarios.
        /// </summary>
        internal static string ExportDialog {
            get {
                return ResourceManager.GetString("ExportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name of file already exists!.
        /// </summary>
        internal static string FileNameAlreadyExists {
            get {
                return ResourceManager.GetString("FileNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string FrequencyLabel {
            get {
                return ResourceManager.GetString("FrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string HeaderHeaderType {
            get {
                return ResourceManager.GetString("HeaderHeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string HeaderHeaderValue {
            get {
                return ResourceManager.GetString("HeaderHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap homepage {
            get {
                object obj = ResourceManager.GetObject("homepage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request name is invalid!.
        /// </summary>
        internal static string InvalidRequestName {
            get {
                return ResourceManager.GetString("InvalidRequestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid scnario name!.
        /// </summary>
        internal static string InvalidScenarioName {
            get {
                return ResourceManager.GetString("InvalidScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be empty!.
        /// </summary>
        internal static string InvalidServerName {
            get {
                return ResourceManager.GetString("InvalidServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server url!.
        /// </summary>
        internal static string InvalidServerURL {
            get {
                return ResourceManager.GetString("InvalidServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delay must be a number and greather or equal to 0!.
        /// </summary>
        internal static string InvalidTimeDelay {
            get {
                return ResourceManager.GetString("InvalidTimeDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Director.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add scenario.
        /// </summary>
        internal static string MenuAddScenario {
            get {
                return ResourceManager.GetString("MenuAddScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy request.
        /// </summary>
        internal static string MenuCopyRequest {
            get {
                return ResourceManager.GetString("MenuCopyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy scenario.
        /// </summary>
        internal static string MenuCopyScenario {
            get {
                return ResourceManager.GetString("MenuCopyScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit default headers.
        /// </summary>
        internal static string MenuEditDefaultHeaders {
            get {
                return ResourceManager.GetString("MenuEditDefaultHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit request.
        /// </summary>
        internal static string MenuEditRequest {
            get {
                return ResourceManager.GetString("MenuEditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExitProgram {
            get {
                return ResourceManager.GetString("MenuExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New server.
        /// </summary>
        internal static string MenuNewServer {
            get {
                return ResourceManager.GetString("MenuNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario.
        /// </summary>
        internal static string MenuOpenScenario {
            get {
                return ResourceManager.GetString("MenuOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste request.
        /// </summary>
        internal static string MenuPasteRequest {
            get {
                return ResourceManager.GetString("MenuPasteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste scenario.
        /// </summary>
        internal static string MenuPasteScenario {
            get {
                return ResourceManager.GetString("MenuPasteScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scenario.
        /// </summary>
        internal static string MenuSaveScenario {
            get {
                return ResourceManager.GetString("MenuSaveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string MenuServer {
            get {
                return ResourceManager.GetString("MenuServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this request?.
        /// </summary>
        internal static string MessageBoxRemoveRequest {
            get {
                return ResourceManager.GetString("MessageBoxRemoveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this scenario?.
        /// </summary>
        internal static string MessageBoxRemoveScenario {
            get {
                return ResourceManager.GetString("MessageBoxRemoveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_server {
            get {
                object obj = ResourceManager.GetObject("new_server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New scenario.
        /// </summary>
        internal static string NewScenarioName {
            get {
                return ResourceManager.GetString("NewScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New server.
        /// </summary>
        internal static string NewServerString {
            get {
                return ResourceManager.GetString("NewServerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.example.com/.
        /// </summary>
        internal static string NewServerURL {
            get {
                return ResourceManager.GetString("NewServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        internal static string NoRequestMethod {
            get {
                return ResourceManager.GetString("NoRequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one scenario to export!.
        /// </summary>
        internal static string NoScenarioSelected {
            get {
                return ResourceManager.GetString("NoScenarioSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        internal static string OrderDOWN {
            get {
                return ResourceManager.GetString("OrderDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        internal static string OrderUP {
            get {
                return ResourceManager.GetString("OrderUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select output file!.
        /// </summary>
        internal static string OutputFileNotSelected {
            get {
                return ResourceManager.GetString("OutputFileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_copy {
            get {
                object obj = ResourceManager.GetObject("page_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_paste {
            get {
                object obj = ResourceManager.GetObject("page_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap processing {
            get {
                object obj = ResourceManager.GetObject("processing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap request {
            get {
                object obj = ResourceManager.GetObject("request", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap request_page {
            get {
                object obj = ResourceManager.GetObject("request_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string RequestFiles {
            get {
                return ResourceManager.GetString("RequestFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string RequestHeaders {
            get {
                return ResourceManager.GetString("RequestHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string RequestInfoBox {
            get {
                return ResourceManager.GetString("RequestInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string RequestMethod {
            get {
                return ResourceManager.GetString("RequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request name.
        /// </summary>
        internal static string RequestName {
            get {
                return ResourceManager.GetString("RequestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string RequestOverview {
            get {
                return ResourceManager.GetString("RequestOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request specification.
        /// </summary>
        internal static string RequestRequest {
            get {
                return ResourceManager.GetString("RequestRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response specification.
        /// </summary>
        internal static string RequestResponse {
            get {
                return ResourceManager.GetString("RequestResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request settings.
        /// </summary>
        internal static string RequestSettings {
            get {
                return ResourceManager.GetString("RequestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string RequestTab {
            get {
                return ResourceManager.GetString("RequestTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string RequestUrl {
            get {
                return ResourceManager.GetString("RequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string ResposneTab {
            get {
                return ResourceManager.GetString("ResposneTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap root {
            get {
                object obj = ResourceManager.GetObject("root", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running options.
        /// </summary>
        internal static string RunningOptionsLabel {
            get {
                return ResourceManager.GetString("RunningOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default running periodicity.
        /// </summary>
        internal static string RunningPeriodicity {
            get {
                return ResourceManager.GetString("RunningPeriodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveServer {
            get {
                return ResourceManager.GetString("SaveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scenario {
            get {
                object obj = ResourceManager.GetObject("scenario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scenario_page {
            get {
                object obj = ResourceManager.GetObject("scenario_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        internal static string ScenarioInfoBox {
            get {
                return ResourceManager.GetString("ScenarioInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        internal static string ScenarioLabel {
            get {
                return ResourceManager.GetString("ScenarioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ScenarioName {
            get {
                return ResourceManager.GetString("ScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario overview.
        /// </summary>
        internal static string ScenarioOverview {
            get {
                return ResourceManager.GetString("ScenarioOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario settings.
        /// </summary>
        internal static string ScenarioSettings {
            get {
                return ResourceManager.GetString("ScenarioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all scenarios.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scenarios to export.
        /// </summary>
        internal static string SelectScenarios {
            get {
                return ResourceManager.GetString("SelectScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server_page {
            get {
                object obj = ResourceManager.GetObject("server_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string ServerInfoBox {
            get {
                return ResourceManager.GetString("ServerInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        internal static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default server URL.
        /// </summary>
        internal static string ServerURL {
            get {
                return ResourceManager.GetString("ServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delay in seconds.
        /// </summary>
        internal static string TimeDelayInSeconds {
            get {
                return ResourceManager.GetString("TimeDelayInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delay after previous scenario.
        /// </summary>
        internal static string TimeDelayLabel {
            get {
                return ResourceManager.GetString("TimeDelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TreeStoreInformation {
            get {
                return ResourceManager.GetString("TreeStoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
