//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Director.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Director.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Director.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_content {
            get {
                object obj = ResourceManager.GetObject("add_content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization settings.
        /// </summary>
        internal static string AuthorizationSettings {
            get {
                return ResourceManager.GetString("AuthorizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_blue {
            get {
                object obj = ResourceManager.GetObject("bullet_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start next scenario, wait until previous finished!.
        /// </summary>
        internal static string CanNotStartScenario {
            get {
                return ResourceManager.GetString("CanNotStartScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose running option.
        /// </summary>
        internal static string ChooseRunningOptions {
            get {
                return ResourceManager.GetString("ChooseRunningOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmInput {
            get {
                return ResourceManager.GetString("ConfirmInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add request.
        /// </summary>
        internal static string ContextMenuAddRequest {
            get {
                return ResourceManager.GetString("ContextMenuAddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove request.
        /// </summary>
        internal static string ContextMenuRemoveRequest {
            get {
                return ResourceManager.GetString("ContextMenuRemoveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove scenario.
        /// </summary>
        internal static string ContextMenuRemoveScenario {
            get {
                return ResourceManager.GetString("ContextMenuRemoveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyInClipboard {
            get {
                return ResourceManager.GetString("CopyInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cs {
            get {
                object obj = ResourceManager.GetObject("cs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap default_headers {
            get {
                object obj = ResourceManager.GetObject("default_headers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default headers.
        /// </summary>
        internal static string DefaultServerHeaders {
            get {
                return ResourceManager.GetString("DefaultServerHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Director file!.
        /// </summary>
        internal static string DialogInvalidFile {
            get {
                return ResourceManager.GetString("DialogInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scenario file.
        /// </summary>
        internal static string DialogOpenScenario {
            get {
                return ResourceManager.GetString("DialogOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scenario.
        /// </summary>
        internal static string DialogSaveScenario {
            get {
                return ResourceManager.GetString("DialogSaveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set content.
        /// </summary>
        internal static string EditContent {
            get {
                return ResourceManager.GetString("EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit variable.
        /// </summary>
        internal static string EditVariable {
            get {
                return ResourceManager.GetString("EditVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notifications.
        /// </summary>
        internal static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request URL!.
        /// </summary>
        internal static string ErroInvalidRequest {
            get {
                return ResourceManager.GetString("ErroInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when generating template.
        /// </summary>
        internal static string ErrorWhenGeneratingTemplate {
            get {
                return ResourceManager.GetString("ErrorWhenGeneratingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 10 minutes.
        /// </summary>
        internal static string Every10Minutes {
            get {
                return ResourceManager.GetString("Every10Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 12 hours.
        /// </summary>
        internal static string Every12Hours {
            get {
                return ResourceManager.GetString("Every12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 30 minutes.
        /// </summary>
        internal static string Every30Minutes {
            get {
                return ResourceManager.GetString("Every30Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 3 hours.
        /// </summary>
        internal static string Every3Hours {
            get {
                return ResourceManager.GetString("Every3Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 5 minutes.
        /// </summary>
        internal static string Every5Minutes {
            get {
                return ResourceManager.GetString("Every5Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6 hours.
        /// </summary>
        internal static string Every6Hours {
            get {
                return ResourceManager.GetString("Every6Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every hour.
        /// </summary>
        internal static string EveryHour {
            get {
                return ResourceManager.GetString("EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected status code.
        /// </summary>
        internal static string ExpectedStatusCode {
            get {
                return ResourceManager.GetString("ExpectedStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during deserialization of scenarios:.
        /// </summary>
        internal static string ExportDeserialScenariosEx {
            get {
                return ResourceManager.GetString("ExportDeserialScenariosEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during deserialization of server:.
        /// </summary>
        internal static string ExportDeserialServerEx {
            get {
                return ResourceManager.GetString("ExportDeserialServerEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export scenarios.
        /// </summary>
        internal static string ExportDialog {
            get {
                return ResourceManager.GetString("ExportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during processing files:.
        /// </summary>
        internal static string ExportProcessFilesEx {
            get {
                return ResourceManager.GetString("ExportProcessFilesEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during processing temporary directory:.
        /// </summary>
        internal static string ExportProcessTempDirEx {
            get {
                return ResourceManager.GetString("ExportProcessTempDirEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export result.
        /// </summary>
        internal static string ExportResult {
            get {
                return ResourceManager.GetString("ExportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during serialization of scenarios:.
        /// </summary>
        internal static string ExportSerialScenariosEx {
            get {
                return ResourceManager.GetString("ExportSerialScenariosEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during serialization of server:.
        /// </summary>
        internal static string ExportSerialServerEx {
            get {
                return ResourceManager.GetString("ExportSerialServerEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} in request {1} in scenario {2} has been skipped.\n.
        /// </summary>
        internal static string ExportSkipFileWarning {
            get {
                return ResourceManager.GetString("ExportSkipFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during a zip compression:.
        /// </summary>
        internal static string ExportZipCompressionEx {
            get {
                return ResourceManager.GetString("ExportZipCompressionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during a zip decompression:.
        /// </summary>
        internal static string ExportZipDecompressionEx {
            get {
                return ResourceManager.GetString("ExportZipDecompressionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name of file already exists!.
        /// </summary>
        internal static string FileNameAlreadyExists {
            get {
                return ResourceManager.GetString("FileNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format directive.
        /// </summary>
        internal static string FormatDirective {
            get {
                return ResourceManager.GetString("FormatDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format guide.
        /// </summary>
        internal static string FormatGuide {
            get {
                return ResourceManager.GetString("FormatGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string FrequencyLabel {
            get {
                return ResourceManager.GetString("FrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap header_edit {
            get {
                object obj = ResourceManager.GetObject("header_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string HeaderHeaderType {
            get {
                return ResourceManager.GetString("HeaderHeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string HeaderHeaderValue {
            get {
                return ResourceManager.GetString("HeaderHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression creator.
        /// </summary>
        internal static string HeaderSettings {
            get {
                return ResourceManager.GetString("HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenuItem {
            get {
                return ResourceManager.GetString("HelpMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap homepage {
            get {
                object obj = ResourceManager.GetObject("homepage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string HomepageUrl {
            get {
                return ResourceManager.GetString("HomepageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons by.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import result.
        /// </summary>
        internal static string ImportResult {
            get {
                return ResourceManager.GetString("ImportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste input:.
        /// </summary>
        internal static string InputPrompt {
            get {
                return ResourceManager.GetString("InputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert {
            get {
                object obj = ResourceManager.GetObject("insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input has to be number!.
        /// </summary>
        internal static string InvalidNumberInput {
            get {
                return ResourceManager.GetString("InvalidNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request name is invalid!.
        /// </summary>
        internal static string InvalidRequestName {
            get {
                return ResourceManager.GetString("InvalidRequestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: {0} code but request ends with: {1}..
        /// </summary>
        internal static string InvalidReturnCode {
            get {
                return ResourceManager.GetString("InvalidReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid scnario name!.
        /// </summary>
        internal static string InvalidScenarioName {
            get {
                return ResourceManager.GetString("InvalidScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be empty!.
        /// </summary>
        internal static string InvalidServerName {
            get {
                return ResourceManager.GetString("InvalidServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server url!.
        /// </summary>
        internal static string InvalidServerURL {
            get {
                return ResourceManager.GetString("InvalidServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status code.
        /// </summary>
        internal static string InvalidStatusCode {
            get {
                return ResourceManager.GetString("InvalidStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delay must be a number and greather or equal to 0!.
        /// </summary>
        internal static string InvalidTimeDelay {
            get {
                return ResourceManager.GetString("InvalidTimeDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time!.
        /// </summary>
        internal static string InvalidWaitTime {
            get {
                return ResourceManager.GetString("InvalidWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string JsonValue {
            get {
                return ResourceManager.GetString("JsonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list {
            get {
                object obj = ResourceManager.GetObject("list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Director.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add scenario.
        /// </summary>
        internal static string MenuAddScenario {
            get {
                return ResourceManager.GetString("MenuAddScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close scenario.
        /// </summary>
        internal static string MenuCloseScenario {
            get {
                return ResourceManager.GetString("MenuCloseScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy request.
        /// </summary>
        internal static string MenuCopyRequest {
            get {
                return ResourceManager.GetString("MenuCopyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy scenario.
        /// </summary>
        internal static string MenuCopyScenario {
            get {
                return ResourceManager.GetString("MenuCopyScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit default headers.
        /// </summary>
        internal static string MenuEditDefaultHeaders {
            get {
                return ResourceManager.GetString("MenuEditDefaultHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit request.
        /// </summary>
        internal static string MenuEditRequest {
            get {
                return ResourceManager.GetString("MenuEditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExitProgram {
            get {
                return ResourceManager.GetString("MenuExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New server.
        /// </summary>
        internal static string MenuNewServer {
            get {
                return ResourceManager.GetString("MenuNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario.
        /// </summary>
        internal static string MenuOpenScenario {
            get {
                return ResourceManager.GetString("MenuOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste request.
        /// </summary>
        internal static string MenuPasteRequest {
            get {
                return ResourceManager.GetString("MenuPasteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste scenario.
        /// </summary>
        internal static string MenuPasteScenario {
            get {
                return ResourceManager.GetString("MenuPasteScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string MenuRun {
            get {
                return ResourceManager.GetString("MenuRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save server.
        /// </summary>
        internal static string MenuSaveServer {
            get {
                return ResourceManager.GetString("MenuSaveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string MenuServer {
            get {
                return ResourceManager.GetString("MenuServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close scenario?.
        /// </summary>
        internal static string MessageBoxCloseScenario {
            get {
                return ResourceManager.GetString("MessageBoxCloseScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this request?.
        /// </summary>
        internal static string MessageBoxRemoveRequest {
            get {
                return ResourceManager.GetString("MessageBoxRemoveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this scenario?.
        /// </summary>
        internal static string MessageBoxRemoveScenario {
            get {
                return ResourceManager.GetString("MessageBoxRemoveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_server {
            get {
                object obj = ResourceManager.GetObject("new_server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        internal static string NewRequestName {
            get {
                return ResourceManager.GetString("NewRequestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New scenario.
        /// </summary>
        internal static string NewScenarioName {
            get {
                return ResourceManager.GetString("NewScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New server.
        /// </summary>
        internal static string NewServerString {
            get {
                return ResourceManager.GetString("NewServerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.example.com/.
        /// </summary>
        internal static string NewServerURL {
            get {
                return ResourceManager.GetString("NewServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        internal static string NoRequestMethod {
            get {
                return ResourceManager.GetString("NoRequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response yet, run scenario first!.
        /// </summary>
        internal static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one scenario to export!.
        /// </summary>
        internal static string NoScenarioSelected {
            get {
                return ResourceManager.GetString("NoScenarioSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no variables in this scenario, make please a new one from successfull request!.
        /// </summary>
        internal static string NoVariablesFound {
            get {
                return ResourceManager.GetString("NoVariablesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkComand {
            get {
                return ResourceManager.GetString("OkComand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        internal static string OrderDOWN {
            get {
                return ResourceManager.GetString("OrderDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        internal static string OrderUP {
            get {
                return ResourceManager.GetString("OrderUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select output file!.
        /// </summary>
        internal static string OutputFileNotSelected {
            get {
                return ResourceManager.GetString("OutputFileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string OutputMessage {
            get {
                return ResourceManager.GetString("OutputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_copy {
            get {
                object obj = ResourceManager.GetObject("page_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_paste {
            get {
                object obj = ResourceManager.GetObject("page_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string PARSER_ERR_MSG_ARGUMENT_INVALID {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_ARGUMENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid float..
        /// </summary>
        internal static string PARSER_ERR_MSG_ARGUMENT_NOT_FLOAT {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_ARGUMENT_NOT_FLOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a valid integer..
        /// </summary>
        internal static string PARSER_ERR_MSG_ARGUMENT_NOT_INTEGER {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_ARGUMENT_NOT_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is too big of a number..
        /// </summary>
        internal static string PARSER_ERR_MSG_ARGUMENT_TOO_BIG {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_ARGUMENT_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument no. {0} (&quot;{1}&quot;) must be smaller than argument no. {2} (&quot;{3}&quot;)..
        /// </summary>
        internal static string PARSER_ERR_MSG_ARGUMENTS_WRONG_SIZED {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_ARGUMENTS_WRONG_SIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &quot;{0} {1} {2}&quot; returned false..
        /// </summary>
        internal static string PARSER_ERR_MSG_COMPARE_OPERATION {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_COMPARE_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types &quot;{0}&quot; defined in template and &quot;{1}&quot; received in response don&apos;t match..
        /// </summary>
        internal static string PARSER_ERR_MSG_COMPARE_TYPES {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_COMPARE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values &quot;{0}&quot; defined in template and &quot;{1}&quot; received in response don&apos;t match..
        /// </summary>
        internal static string PARSER_ERR_MSG_COMPARE_VALUES {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_COMPARE_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting &quot;{0}&quot;..
        /// </summary>
        internal static string PARSER_ERR_MSG_EXPECTING_CHARACTER {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_EXPECTING_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal function definition inside variable name..
        /// </summary>
        internal static string PARSER_ERR_MSG_FN_INSIDE_VAR {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_FN_INSIDE_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response JSON contains &quot;{0}&quot; key, that is not defined in the template..
        /// </summary>
        internal static string PARSER_ERR_MSG_ILLEGAL_KEY_IN_RESPONSE {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_ILLEGAL_KEY_IN_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &quot;{0}&quot;..
        /// </summary>
        internal static string PARSER_ERR_MSG_INVALID_CHARACTER {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_INVALID_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of arguments..
        /// </summary>
        internal static string PARSER_ERR_MSG_INVALID_NUMBER_OF_ARGUMENTS {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_INVALID_NUMBER_OF_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing type for operation. If you want to compare the value, type must be specified..
        /// </summary>
        internal static string PARSER_ERR_MSG_MISING_TYPE_FOR_OPERATION {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_MISING_TYPE_FOR_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing function name..
        /// </summary>
        internal static string PARSER_ERR_MSG_MISSING_FN_NAME {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_MISSING_FN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response JSON does not contain &quot;{0}&quot; key, that is defined as mandatory in the template..
        /// </summary>
        internal static string PARSER_ERR_MSG_MISSING_KEY_IN_RESPONSE {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_MISSING_KEY_IN_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closing function character ({0}). Either provide one or escape this one like {1} ..
        /// </summary>
        internal static string PARSER_ERR_MSG_MISSING_MAIN_SYNTAX_CHARACTER {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_MISSING_MAIN_SYNTAX_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closing variable character ({0}). Either provide one or escape this one like {1} ..
        /// </summary>
        internal static string PARSER_ERR_MSG_MISSING_VARIABLE_CHARACTER {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_MISSING_VARIABLE_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &quot;{0}&quot; does not support &quot;{1}&quot; type..
        /// </summary>
        internal static string PARSER_ERR_MSG_OPERATION_DOESNT_SUPPORT_TYPE {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_OPERATION_DOESNT_SUPPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression parser raised following exception: {0}.
        /// </summary>
        internal static string PARSER_ERR_MSG_REGEX_PARSER {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_REGEX_PARSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible swapped parentheses - &quot;{0}&quot; must be closed with &quot;{1}&quot;..
        /// </summary>
        internal static string PARSER_ERR_MSG_SWAPPED_PARENTHESES {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_SWAPPED_PARENTHESES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; is not defined..
        /// </summary>
        internal static string PARSER_ERR_MSG_UNKNOWN_CUSTOM_VARIABLE {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_UNKNOWN_CUSTOM_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operation type &quot;{0}&quot;..
        /// </summary>
        internal static string PARSER_ERR_MSG_UNKNOWN_OPERATION {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_UNKNOWN_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type &quot;{0}&quot;..
        /// </summary>
        internal static string PARSER_ERR_MSG_UNKNOWN_TYPE {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_UNKNOWN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized characters after defined function..
        /// </summary>
        internal static string PARSER_ERR_MSG_UNRECOGNIZED_CHARS_AFTER_FN {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_UNRECOGNIZED_CHARS_AFTER_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized function..
        /// </summary>
        internal static string PARSER_ERR_MSG_UNRECOGNIZED_FN {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_UNRECOGNIZED_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided value &quot;{0}&quot; couldn&apos;t be converted to &quot;{1}&quot; type..
        /// </summary>
        internal static string PARSER_ERR_MSG_VALUE_UNCONVERTABLE_TO_TYPE {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_VALUE_UNCONVERTABLE_TO_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values for matched key &quot;{0}&quot; differ in their type (&quot;{1}&quot; and &quot;{2}&quot;)..
        /// </summary>
        internal static string PARSER_ERR_MSG_VALUES_DIFFER_IN_TYPE {
            get {
                return ResourceManager.GetString("PARSER_ERR_MSG_VALUES_DIFFER_IN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste input:.
        /// </summary>
        internal static string PasteInput {
            get {
                return ResourceManager.GetString("PasteInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap processing {
            get {
                object obj = ResourceManager.GetObject("processing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap request {
            get {
                object obj = ResourceManager.GetObject("request", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap request_page {
            get {
                object obj = ResourceManager.GetObject("request_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request content:.
        /// </summary>
        internal static string RequestContent {
            get {
                return ResourceManager.GetString("RequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string RequestFiles {
            get {
                return ResourceManager.GetString("RequestFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string RequestHeaders {
            get {
                return ResourceManager.GetString("RequestHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string RequestInfoBox {
            get {
                return ResourceManager.GetString("RequestInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string RequestMethod {
            get {
                return ResourceManager.GetString("RequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request name.
        /// </summary>
        internal static string RequestName {
            get {
                return ResourceManager.GetString("RequestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was not successfull ({0})!.
        /// </summary>
        internal static string RequestNotSuccessfull {
            get {
                return ResourceManager.GetString("RequestNotSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string RequestOverview {
            get {
                return ResourceManager.GetString("RequestOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request specification.
        /// </summary>
        internal static string RequestRequest {
            get {
                return ResourceManager.GetString("RequestRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response specification.
        /// </summary>
        internal static string RequestResponse {
            get {
                return ResourceManager.GetString("RequestResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request settings.
        /// </summary>
        internal static string RequestSettings {
            get {
                return ResourceManager.GetString("RequestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string RequestTab {
            get {
                return ResourceManager.GetString("RequestTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request template.
        /// </summary>
        internal static string RequestTemplate {
            get {
                return ResourceManager.GetString("RequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string RequestUrl {
            get {
                return ResourceManager.GetString("RequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response content.
        /// </summary>
        internal static string ResponseContent {
            get {
                return ResourceManager.GetString("ResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response template.
        /// </summary>
        internal static string ResponseTemplate {
            get {
                return ResourceManager.GetString("ResponseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string ResposneTab {
            get {
                return ResourceManager.GetString("ResposneTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For apply changes, you have to restart application!.
        /// </summary>
        internal static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result body.
        /// </summary>
        internal static string ResultBody {
            get {
                return ResourceManager.GetString("ResultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is OK.
        /// </summary>
        internal static string ResultIsOk {
            get {
                return ResourceManager.GetString("ResultIsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap root {
            get {
                object obj = ResourceManager.GetObject("root", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all!.
        /// </summary>
        internal static string RunAllMenu {
            get {
                return ResourceManager.GetString("RunAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running options.
        /// </summary>
        internal static string RunningOptionsLabel {
            get {
                return ResourceManager.GetString("RunningOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default running periodicity.
        /// </summary>
        internal static string RunningPeriodicity {
            get {
                return ResourceManager.GetString("RunningPeriodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run scenario.
        /// </summary>
        internal static string RunScenario {
            get {
                return ResourceManager.GetString("RunScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveServer {
            get {
                return ResourceManager.GetString("SaveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scenario {
            get {
                object obj = ResourceManager.GetObject("scenario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scenario_page {
            get {
                object obj = ResourceManager.GetObject("scenario_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        internal static string ScenarioInfoBox {
            get {
                return ResourceManager.GetString("ScenarioInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        internal static string ScenarioLabel {
            get {
                return ResourceManager.GetString("ScenarioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ScenarioName {
            get {
                return ResourceManager.GetString("ScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario overview.
        /// </summary>
        internal static string ScenarioOverview {
            get {
                return ResourceManager.GetString("ScenarioOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario settings.
        /// </summary>
        internal static string ScenarioSettings {
            get {
                return ResourceManager.GetString("ScenarioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all scenarios.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scenarios to export.
        /// </summary>
        internal static string SelectScenarios {
            get {
                return ResourceManager.GetString("SelectScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server_page {
            get {
                object obj = ResourceManager.GetObject("server_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string ServerInfoBox {
            get {
                return ResourceManager.GetString("ServerInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        internal static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default server URL.
        /// </summary>
        internal static string ServerURL {
            get {
                return ResourceManager.GetString("ServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set request or response.
        /// </summary>
        internal static string SetContentTitle {
            get {
                return ResourceManager.GetString("SetContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splashscreen {
            get {
                object obj = ResourceManager.GetObject("splashscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text after.
        /// </summary>
        internal static string TextAfter {
            get {
                return ResourceManager.GetString("TextAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text before.
        /// </summary>
        internal static string TextBefore {
            get {
                return ResourceManager.GetString("TextBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delay in seconds.
        /// </summary>
        internal static string TimeDelayInSeconds {
            get {
                return ResourceManager.GetString("TimeDelayInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delay after previous scenario.
        /// </summary>
        internal static string TimeDelayLabel {
            get {
                return ResourceManager.GetString("TimeDelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TreeStoreInformation {
            get {
                return ResourceManager.GetString("TreeStoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait in seconds after sucessfull previous request:.
        /// </summary>
        internal static string WaitPreviousRequest {
            get {
                return ResourceManager.GetString("WaitPreviousRequest", resourceCulture);
            }
        }
    }
}
