//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Director.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Director.Locales.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization settings.
        /// </summary>
        public static string AuthorizationSettings {
            get {
                return ResourceManager.GetString("AuthorizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add request.
        /// </summary>
        public static string ContextMenuAddRequest {
            get {
                return ResourceManager.GetString("ContextMenuAddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove request.
        /// </summary>
        public static string ContextMenuRemoveRequest {
            get {
                return ResourceManager.GetString("ContextMenuRemoveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove scenario.
        /// </summary>
        public static string ContextMenuRemoveScenario {
            get {
                return ResourceManager.GetString("ContextMenuRemoveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scenario file.
        /// </summary>
        public static string DialogOpenScenario {
            get {
                return ResourceManager.GetString("DialogOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notifications.
        /// </summary>
        public static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 10 minutes.
        /// </summary>
        public static string Every10Minutes {
            get {
                return ResourceManager.GetString("Every10Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 12 hours.
        /// </summary>
        public static string Every12Hours {
            get {
                return ResourceManager.GetString("Every12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 30 minutes.
        /// </summary>
        public static string Every30Minutes {
            get {
                return ResourceManager.GetString("Every30Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 3 hours.
        /// </summary>
        public static string Every3Hours {
            get {
                return ResourceManager.GetString("Every3Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 5 minutes.
        /// </summary>
        public static string Every5Minutes {
            get {
                return ResourceManager.GetString("Every5Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6 hours.
        /// </summary>
        public static string Every6Hours {
            get {
                return ResourceManager.GetString("Every6Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        public static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every hour.
        /// </summary>
        public static string EveryHour {
            get {
                return ResourceManager.GetString("EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export scenario.
        /// </summary>
        public static string ExportDialog {
            get {
                return ResourceManager.GetString("ExportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid scnario name!.
        /// </summary>
        public static string InvalidScenarioName {
            get {
                return ResourceManager.GetString("InvalidScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be empty!.
        /// </summary>
        public static string InvalidServerName {
            get {
                return ResourceManager.GetString("InvalidServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server url!.
        /// </summary>
        public static string InvalidServerURL {
            get {
                return ResourceManager.GetString("InvalidServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Director.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add scenario.
        /// </summary>
        public static string MenuAddScenario {
            get {
                return ResourceManager.GetString("MenuAddScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExitProgram {
            get {
                return ResourceManager.GetString("MenuExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New server.
        /// </summary>
        public static string MenuNewServer {
            get {
                return ResourceManager.GetString("MenuNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario.
        /// </summary>
        public static string MenuOpenScenario {
            get {
                return ResourceManager.GetString("MenuOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scenario.
        /// </summary>
        public static string MenuSaveScenario {
            get {
                return ResourceManager.GetString("MenuSaveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string MenuServer {
            get {
                return ResourceManager.GetString("MenuServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this scenario?.
        /// </summary>
        public static string MessageBoxRemoveScenario {
            get {
                return ResourceManager.GetString("MessageBoxRemoveScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New scenario.
        /// </summary>
        public static string NewScenarioName {
            get {
                return ResourceManager.GetString("NewScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New server.
        /// </summary>
        public static string NewServerString {
            get {
                return ResourceManager.GetString("NewServerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.example.com/.
        /// </summary>
        public static string NewServerURL {
            get {
                return ResourceManager.GetString("NewServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string RequestInfoBox {
            get {
                return ResourceManager.GetString("RequestInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default running periodicity.
        /// </summary>
        public static string RunningPeriodicity {
            get {
                return ResourceManager.GetString("RunningPeriodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string ScenarioInfoBox {
            get {
                return ResourceManager.GetString("ScenarioInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ScenarioName {
            get {
                return ResourceManager.GetString("ScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario settings.
        /// </summary>
        public static string ScenarioSettings {
            get {
                return ResourceManager.GetString("ScenarioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerInfoBox {
            get {
                return ResourceManager.GetString("ServerInfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        public static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default server URL.
        /// </summary>
        public static string ServerURL {
            get {
                return ResourceManager.GetString("ServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TreeStoreInformation {
            get {
                return ResourceManager.GetString("TreeStoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
